apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: linus-node-rg
    service.beta.kubernetes.io/azure-dns-label-name: lb-7d025dd8-8715-83d4-d06e-960c0ca6e751
  name: helloweb
  namespace: default
spec:
  loadBalancerIP: 4.184.96.94
  type: LoadBalancer
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8443
  selector:
      app: hello
      tier: web
