apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: btc-linusweigand-com
  namespace: default
spec:
  secretName: btc-linusweigand-com-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.btc.linusweigand.com"
  dnsNames:
    - "btc.linusweigand.com"
    - "*.btc.linusweigand.com"