apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: $NODE_RESOURCE_GROUP
    service.beta.kubernetes.io/azure-dns-label-name: $DNS_LABEL_NAME
  name: helloweb
  namespace: default
spec:
  loadBalancerIP: $LOAD_BALANCER_IP
  type: LoadBalancer
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8443
  selector:
      app: hello
      tier: web
