apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front
  annotations:
    service.kubernetes.io/azure-load-balancer-resource-group: $NODE_RESOURCE_GROUP
spec:
  loadBalancerIP: $LOAD_BALANCER_IP
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: azure-vote-front


