apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${name}
  namespace: ${namespace}
spec:
  secretName: ${name}-tls
  commonName: ${domain}
  dnsNames:
  - ${domain}
  issuerRef:
    name: ${issuer}
    kind: ClusterIssuer
