apiVersion: v1
kind: Pod
metadata:
  name: keycloak
  namespace: default
spec:
  containers:
    - name: keycloak
      image: acr187.azurecr.io/keycloak:v1
      imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - name: acr-secret
