apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${name}
  namespace: ${namespace}
spec:
  secretName: ${name}
  privateKey:
    rotationPolicy: Always
  commonName: ${common_name}
  dnsNames:
    - ${dns_name}
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: ${issuer_ref_name}
    kind: ClusterIssuer